language: node_js
node_js:
  - "12"
dist: xenial
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master